# Generated by Django 5.1.2 on 2024-12-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('new_customer', 'New Customer'), ('insured_customer', 'Insured Customer')], default='new_customer', max_length=50),
        ),
    ]
