# Generated by Django 4.2.18 on 2025-01-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cashier', 'Cashier'), ('claim_officer', 'Claim Officer'), ('underwriter', 'Underwriter'), ('new_customer', 'New Customer'), ('insured_customer', 'Insured Customer')], default='new_customer', max_length=50),
        ),
    ]
