# Generated by Django 4.2.18 on 2025-01-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_city_remove_user_postal_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cashier', 'Cashier'), ('claim_officer', 'Claim Officer'), ('underwriter', 'Underwriter'), ('new_customer', 'New Customer')], default='new_customer', max_length=50),
        ),
    ]
