# Generated by Django 5.1.2 on 2024-12-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_newcustomer_vehicle'),
        ('policies', '0002_alter_insurancepolicy_policy_holder'),
        ('vehicle', '0003_vehicle_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsurancePolicy',
            new_name='Policy',
        ),
    ]
