# Generated by Django 4.2.18 on 2025-02-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_rename_insurancepolicy_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='insured_name',
        ),
    ]
