# Generated by Django 4.2.18 on 2025-02-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_remove_policy_insured_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(editable=False, help_text='Unique policy number.', max_length=20, unique=True),
        ),
    ]
