# Generated by Django 4.2.18 on 2025-02-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_alter_policy_policy_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('Comprehensive', 'Comprehensive'), ('Third-Party', 'Third-Party'), ('Fire and Theft', 'Fire and Theft')], help_text='Type of insurance policy.', max_length=30),
        ),
    ]
