# Generated by Django 4.2.18 on 2025-01-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_claim_claimant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='estimated_damage_cost',
        ),
        migrations.AddField(
            model_name='claim',
            name='settlement_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount for settlement approved by claim officer.', max_digits=10, null=True),
        ),
    ]
