# Generated by Django 4.2.18 on 2025-02-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_remove_claim_estimated_damage_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='estimated_damage_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
