# Generated by Django 4.2.18 on 2025-02-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_claim_estimated_damage_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='description',
            field=models.TextField(help_text='Detailed description of the accident and claim.', null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='police_report_number',
            field=models.CharField(blank=True, default='', help_text='Police report reference, if applicable.', max_length=50),
            preserve_default=False,
        ),
    ]
