# Generated by Django 4.2.18 on 2025-02-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_alter_claim_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='claimant',
        ),
    ]
