# Generated by Django 4.2.18 on 2025-02-10 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_remove_claim_claimant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='claim_officer',
        ),
    ]
