# Generated by Django 5.1.2 on 2024-12-16 19:12

import django.db.models.deletion
import risk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_rename_newcutomer_insuredcustomer_newcustomer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_factor', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', help_text='Predicted risk score from the AI.', max_length=6)),
                ('claim_likelihood', models.DecimalField(decimal_places=2, max_digits=5, validators=[risk.models.validate_claim_likelihood])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insuredcustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riskassessment', to='accounts.insuredcustomer')),
            ],
        ),
    ]
