# Generated by Django 5.1.2 on 2024-12-23 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_insuredcustomer_newcustomer'),
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='insuredcustomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riskassessment', to='accounts.newcustomer'),
        ),
    ]
