# Generated by Django 4.2.18 on 2025-02-10 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('risk', '0002_alter_riskassessment_insuredcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='insuredcustomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riskassessment', to=settings.AUTH_USER_MODEL),
        ),
    ]
