# Generated by Django 4.2.18 on 2025-02-10 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_vehicle_customer'),
        ('risk', '0003_alter_riskassessment_insuredcustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskassessment',
            name='insuredcustomer',
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='vehicle',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='riskassessment', to='vehicle.vehicle'),
            preserve_default=False,
        ),
    ]
