# Generated by Django 5.1.2 on 2024-12-14 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_newcustomer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuredCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newcutomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insuredcustomer', to='accounts.newcustomer')),
            ],
        ),
    ]
