# Generated by Django 5.1.2 on 2024-12-16 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_insuredcustomer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insuredcustomer',
            old_name='newcutomer',
            new_name='newcustomer',
        ),
        migrations.RemoveField(
            model_name='newcustomer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='newcustomer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='newcustomer',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='newcustomer',
            name='state',
        ),
    ]
