# Generated by Django 5.1.2 on 2024-12-23 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_newcutomer_insuredcustomer_newcustomer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuredcustomer',
            name='newcustomer',
        ),
    ]
