# Generated by Django 5.1.2 on 2024-12-23 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_insuredcustomer_newcustomer'),
        ('claims', '0003_alter_claim_claimant'),
        ('risk', '0002_alter_riskassessment_insuredcustomer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsuredCustomer',
        ),
    ]
