# Generated by Django 4.2.18 on 2025-01-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_newcustomer_city_newcustomer_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcustomer',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Insured', 'Insured'), ('Rejected', 'Rejected')], default='New', max_length=50),
        ),
    ]
