# Generated by Django 4.2.18 on 2025-01-29 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_vehicle_customer'),
        ('accounts', '0010_newcustomer_owner_name_newcustomer_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcustomer',
            name='vehicles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='vehicle.vehicle'),
        ),
    ]
