# Generated by Django 4.2.18 on 2025-01-29 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_vehicle_customer'),
        ('accounts', '0011_newcustomer_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcustomer',
            name='drivers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='vehicle.driver'),
        ),
    ]
