# Generated by Django 5.1.2 on 2024-12-03 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='vehicle.vehicle'),
            preserve_default=False,
        ),
    ]
