# Generated by Django 5.1.2 on 2024-12-23 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_insuredcustomer'),
        ('vehicle', '0002_driver_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle', to='accounts.newcustomer'),
            preserve_default=False,
        ),
    ]
